// import Head from 'next/head';
// import Image from 'next/image';
import Link from 'next/link';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      {/* <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head> */}

      <h1>Home Page</h1>
      {/* Link does not provide us style attribute and we need to add it to 'a' tag */}
      <Link href={'/blog'}>
        <a style={{ display: 'block' }}>Blog</a>
      </Link>
      <Link href={'/product'}>Product</Link>
    </div>
  );
}
